### ISSUE TITLE
/bash_loading_animations.sh: line 60: `BLA::play_loading_animation_loop': not a valid identifier

### ISSUE THREAD

**Issue by sdarioz** [Silejonu/bash_loading_animations#3]
I have this problem when executing my script

❯ sh test.sh
"../bash_loading_animations/bash_loading_animations.sh: line 60: `BLA::play_loading_animation_loop': not a valid identifier"

**Comment by Silejonu** [comment]
Please share your script here, this error suggests there is something wrong in it.

**Comment by sdarioz** [comment]
```

> Please share your script here, this error suggests there is something wrong in it.


# Load in the functions and animations
source /var/www/html/bash_ls.sh
# Run BLA::stop_loading_animation if the script is interrupted
trap BLA::stop_loading_animation SIGINT

BLA::start_loading_animation "${BLA_braille_whitespace[@]}"

echo "Please write your exact working directory, for example: /var/www/html"
read INPUT_W_DIR

#Vars
W_DIR=$(pwd)

# $W_DIR= "/var/www/html"

# Checks if you're at working directory
if [[ $INPUT_W_DIR == $W_DIR ]]; then
    echo "Working directory path is correct (/var/www/html)"
    
elif [[ $INPUT_W_DIR != $W_DIR ]]; then
    echo "Change your working directory to /var/www/html"

    You're at: `pwd`

    And execute this script again"
    exit 1
    
fi
BLA::stop_loading_animation
```

**Comment by Silejonu** [comment]
I get errors in your script, but the loading animation is present.

Are you sure `source /var/www/html/bash_ls.sh` is right?

How did you download [bash_loading_animation](https://raw.githubusercontent.com/Silejonu/bash_loading_animations/main/bash_loading_animations.sh)? Did you modify it?

**Comment by Silejonu** [comment]
Never mind, I did not pay enough attention to your initial message. The error is caused by the fact you run your script with `sh`. Run it with `bash`, and it will work.

**Comment by falconxperto** [comment]
Awesome, now works! Thank you
![AnyDesk_4](https://user-images.githubusercontent.com/28918294/175345256-fe5555ff-4159-4f7e-89f4-6fa555879b77.png)
!

**Comment by sdarioz** [comment]
Awesome, now works!

`bash_loading_animations/bash_loading_animations.sh: line 72: 2859839 Terminated              BLA::play_loading_animation_loop`

**Comment by sdarioz** [comment]
Thank you!
